package engine.actions;


public enum ActionType {
    DIE,
    EXPLODE_IN_FRAGMENTS,
    GO_INSIDE,
    MOVE,
    NO_MOVE,
    MOVE_REBOUND_IN_EAST,
    MOVE_REBOUND_IN_WEST,
    MOVE_REBOUND_IN_NORTH,
    MOVE_REBOUND_IN_SOUTH,
    SPAWN_BODY,
    SPAWN_PROJECTILE,
    MOVE_TO_CENTER,
    COLLECT_COIN  // ← NUEVO
}
